[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
[project]
name = "vdx_py"
description = "Python package for index tracking in CasADi "
license = {file = "LICENCE"}
readme = "README.md"
version = "0.0.1"
authors = [
  {name = "Anton E. Pozharskiy", email = "anton.pozharskiy@imtek.uni-freiburg.de"},
]
maintainers = [
  {name = "Anton E. Pozharskiy", email = "anton.pozharskiy@imtek.uni-freiburg.de"}
]
dependencies = [
    "casadi",
    "numpy",
    "sortedcontainers",
    "termcolor"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]